### PR TITLE
Hello World In R programming Languange

### PR DESCRIPTION
**Pull request by KushalMehta39**

### CODE REVIEW

**Comment by KushalMehta39** [comment]
> _No description provided._
Hey @indranil32  I am participating in Hacktoberfest 2021.
Please Review and revert me back. Thank you.

**Review by indranil32 — CHANGES_REQUESTED** [review]
The README must contain PREREQUISITE instructions for software/sdk/ide required to run the program with (possible links)
and a RUN section telling the CLI or IDE or web way to execute the code

**Comment by KushalMehta39** [comment]
> The README must contain PREREQUISITE instructions for software/sdk/ide required to run the program with (possible links) and a RUN section telling the CLI or IDE or web way to execute the code

Okay I am working on it.

**Comment by KushalMehta39** [comment]
@indranil32 
Check this Readme.md and revert me back if you need any more changes

**Review by indranil32 — CHANGES_REQUESTED** [review]
The folder is wrong- it should be R not ICON
Also, it seems R is already done. Submit for some other language.

**Comment by KushalMehta39** [comment]
> The folder is wrong- it should be R not ICON Also, it seems R is already done. Submit for some other language.

Okay Thanks Let me try another then.

**Comment by KushalMehta39** [comment]
I Have Changed language and make a new PR Thanks

**Pull request closed without merging**
