### PR TITLE
Added HelloWorld In HTML

### PR DESCRIPTION
**Pull request by SamyakJain2020**
Added Hello World in HTML And CSS With Readme.md

image

### CODE REVIEW

**Review by indranil32 — CHANGES_REQUESTED** [review]
PREREQUISITE is either having a browser or VSCODE, please add that

Please mention -> Open index.html in browser (otherwise opening in text editors won't work)

**Comment by SamyakJain2020** [comment]
OK Sure Will Make the Changes.

**Comment by SamyakJain2020** [comment]
Please assign me this Issue if you can

**Review by SamyakJain2020 — COMMENTED** [review]
Corrected Readme

**Review by indranil32 — APPROVED** [review]

**Pull request merged**
